---
api_keys:
  slack: "$SLACK_TOKEN"
  pagerduty:
    org: "$PAGERDUTY_ORG"
    key: "$PAGERDUTY_KEY"

groups:
- name: paas-oncall
  schedules:
  - "P3DWX7O" # PaaS On-Call Weekly
  update_message:
    message: "Updated @paas-oncall members: %s"
    channels:
    - paas
