---
api_keys:
  slack: "$SLACK_TOKEN"
  pagerduty:
    org: "$PAGERDUTY_ORG"
    key: "$PAGERDUTY_KEY"

groups:
- name: "myteam-oncall" # Slack Group Name
  schedules:
  - "ABC1234" # PagerDuty Schedule ID
  update_message:
    message: "Updated @myteam-oncall members: %s" # Update message to send to Slack 
    channels:
    - "myteam" # Slack Channel Name
